import { useEffect, useMemo, useState } from "react";
import { Alert, FlatList, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { Avatar, GhostButton, PrimaryButton, ScreenHeader, SpectrumCard, StatusBadge, SurfaceCard } from "@/components/gym-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useGym } from "@/lib/gym-store";
import { haptic } from "@/lib/haptics";
import { createLocalDateRail, formatLocalClock, isSameLocalDay, isUpcomingAtLocalTime } from "@/lib/scheduler";
import { formatShortDate, formatTime, getCoach, getService, type TimeSlot } from "@/shared/gym";

export default function BookScreen() {
  const colors = useColors();
  const { snapshot, bookSlot } = useGym();
  const [now, setNow] = useState(() => new Date());
  const [selectedDay, setSelectedDay] = useState(0);
  const [selectedService, setSelectedService] = useState("all");
  const [selectedCoach, setSelectedCoach] = useState("all");
  const [selectedSlot, setSelectedSlot] = useState<TimeSlot | null>(null);
  const [showFilters, setShowFilters] = useState(false);
  const [busy, setBusy] = useState(false);

  useEffect(() => { const timer = setInterval(() => setNow(new Date()), 30_000); return () => clearInterval(timer); }, []);
  const days = createLocalDateRail(now, 7);
  const selectedDate = days[selectedDay] ?? days[0];
  const isToday = isSameLocalDay(selectedDate, now);
  const slots = useMemo(() => snapshot.slots.filter((slot) => isSameLocalDay(new Date(slot.start), selectedDate) && slot.status === "Open" && isUpcomingAtLocalTime(slot.start, now) && (selectedService === "all" || slot.serviceTypeId === selectedService) && (selectedCoach === "all" || slot.coachId === selectedCoach)).sort((left, right) => new Date(left.start).getTime() - new Date(right.start).getTime()), [snapshot.slots, selectedDate, now, selectedService, selectedCoach]);
  const selectedServiceName = selectedService === "all" ? "Any session" : getService(snapshot, selectedService)?.name ?? "Any session";
  const selectedCoachName = selectedCoach === "all" ? "Any coach" : getCoach(snapshot, selectedCoach)?.fullName ?? "Any coach";
  const hasFilters = selectedService !== "all" || selectedCoach !== "all";
  const clearFilters = () => { setSelectedService("all"); setSelectedCoach("all"); };
  const resetToToday = () => { setNow(new Date()); setSelectedDay(0); };
  const handleBook = async () => { if (!selectedSlot) return; setBusy(true); const result = await bookSlot(selectedSlot.id); setBusy(false); setSelectedSlot(null); if (result.success) haptic.success(); else haptic.error(); Alert.alert(result.success ? "You’re booked" : "Couldn’t book that session", result.success ? result.message : result.error); };

  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}>
    <FlatList data={slots} keyExtractor={(slot) => slot.id} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ListHeaderComponent={<View style={styles.headerContent}>
      <ScreenHeader title="Book a session" subtitle="Pick a day, then choose the time that works." label="AVAILABILITY" />
      <SpectrumCard style={styles.clockCard} intensity="muted"><View><Text style={styles.clockEyebrow}>YOUR LOCAL TIME</Text><Text style={styles.clockTitle}>{isToday ? "Today" : formatShortDate(selectedDate.toISOString())}</Text><Text style={styles.clockMeta}>{formatLocalClock(now)} · Past sessions are hidden</Text></View>{!isToday ? <Pressable onPress={resetToToday} style={({ pressed }) => [styles.todayButton, pressed && styles.pressed]} accessibilityRole="button"><Text style={styles.todayText}>Today</Text></Pressable> : <StatusBadge label="Live" tone="success" />}</SpectrumCard>
      <StepTitle number="1" title="Pick a day" detail={isToday ? "Today’s availability" : formatShortDate(selectedDate.toISOString())} />
      <FlatList horizontal data={days} keyExtractor={(day) => `${day.getFullYear()}-${day.getMonth()}-${day.getDate()}`} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.dateStrip} renderItem={({ item: day, index }) => { const active = selectedDay === index; const today = isSameLocalDay(day, now); return <Pressable onPress={() => setSelectedDay(index)} style={({ pressed }) => [styles.dateCard, { backgroundColor: active ? "#2b1f2a" : colors.surface, borderColor: active ? "#f04488" : colors.border }, pressed && styles.pressed]} accessibilityRole="button" accessibilityLabel={`Select ${day.toDateString()}`}><Text style={[styles.dateWeekday, { color: active ? "#ff82b7" : colors.muted }]}>{today ? "TODAY" : new Intl.DateTimeFormat("en-US", { weekday: "short" }).format(day).toUpperCase()}</Text><Text style={[styles.dateNumber, { color: colors.foreground }]}>{day.getDate()}</Text>{today ? <View style={styles.todayDot} /> : null}</Pressable>; }} />
      <StepTitle number="2" title="Refine your options" detail="Optional" />
      <SurfaceCard style={styles.filterSummary} onPress={() => setShowFilters(true)} accessibilityLabel="Choose a session type or coach"><View style={styles.filterSummaryCopy}><Text style={[styles.filterSummaryTitle, { color: colors.foreground }]}>{selectedServiceName}</Text><Text style={[styles.filterSummaryDetail, { color: colors.muted }]}>{selectedCoachName}</Text></View><View style={styles.filterSummaryControl}><Text style={styles.filterSummaryControlText}>{hasFilters ? "Edit" : "Choose"}</Text><Text style={styles.filterSummaryArrow}>›</Text></View></SurfaceCard>
      <StepTitle number="3" title="Choose a time" detail={`${slots.length} open`} />
    </View>} ListEmptyComponent={<EmptyAvailability isToday={isToday} hasFilters={hasFilters} onBrowseTomorrow={() => setSelectedDay(Math.min(1, days.length - 1))} onClearFilters={clearFilters} />} ItemSeparatorComponent={() => <View style={styles.itemSeparator} />} renderItem={({ item: slot }) => <SlotCard slot={slot} colors={colors} snapshot={snapshot} onPress={() => setSelectedSlot(slot)} />} />
    <FilterSheet visible={showFilters} colors={colors} snapshot={snapshot} selectedService={selectedService} selectedCoach={selectedCoach} onSelectService={setSelectedService} onSelectCoach={setSelectedCoach} onClear={clearFilters} onClose={() => setShowFilters(false)} />
    <BookingSheet selectedSlot={selectedSlot} colors={colors} snapshot={snapshot} busy={busy} onClose={() => setSelectedSlot(null)} onBook={handleBook} />
  </ScreenContainer>;
}

function StepTitle({ number, title, detail }: { number: string; title: string; detail: string }) { const colors = useColors(); return <View style={styles.stepHeader}><View style={styles.stepNumber}><Text style={styles.stepNumberText}>{number}</Text></View><View style={styles.stepCopy}><Text style={[styles.stepTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.stepDetail, { color: colors.muted }]}>{detail}</Text></View></View>; }

function SlotCard({ slot, colors, snapshot, onPress }: { slot: TimeSlot; colors: ReturnType<typeof useColors>; snapshot: ReturnType<typeof useGym>["snapshot"]; onPress: () => void }) { const service = getService(snapshot, slot.serviceTypeId); const coach = getCoach(snapshot, slot.coachId); const remaining = slot.maximumCapacity - slot.bookedCount; return <SurfaceCard style={styles.slotCard} onPress={onPress} accessibilityLabel={`Book ${service?.name ?? "session"} at ${formatTime(slot.start)}`}><View style={styles.slotTop}><View><Text style={[styles.slotTime, { color: colors.foreground }]}>{formatTime(slot.start)}</Text><Text style={[styles.slotEnd, { color: colors.muted }]}>{service?.durationMinutes} min · {slot.room}</Text></View><StatusBadge label={`${remaining} left`} tone={remaining <= 2 ? "warning" : "success"} /></View><View style={[styles.slotRule, { backgroundColor: colors.border }]} /><View style={styles.slotBottom}>{coach ? <Avatar initials={coach.initials} accent={coach.accent} size={34} /> : <View style={styles.openGymIcon}><Text style={styles.openGymText}>⌁</Text></View>}<View style={styles.slotCopy}><Text style={[styles.slotService, { color: colors.foreground }]}>{service?.name}</Text><Text style={[styles.slotCoach, { color: colors.muted }]}>{coach?.fullName ?? "Self-guided access"}</Text></View><Text style={styles.slotArrow}>→</Text></View></SurfaceCard>; }

function EmptyAvailability({ isToday, hasFilters, onBrowseTomorrow, onClearFilters }: { isToday: boolean; hasFilters: boolean; onBrowseTomorrow: () => void; onClearFilters: () => void }) { const colors = useColors(); const title = isToday ? "No more sessions today" : hasFilters ? "No matches for these options" : "Nothing open on this day"; const copy = isToday ? "All remaining sessions have started or are full. Try another day to keep your rhythm going." : hasFilters ? "Try a different session type or coach to see more availability." : "Pick another day or return later for new availability."; return <SurfaceCard style={styles.emptyCard}><Text style={[styles.emptyTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.emptyMessage, { color: colors.muted }]}>{copy}</Text><GhostButton title={isToday || !hasFilters ? "Browse tomorrow" : "Clear options"} onPress={isToday || !hasFilters ? onBrowseTomorrow : onClearFilters} /></SurfaceCard>; }

function FilterSheet({ visible, colors, snapshot, selectedService, selectedCoach, onSelectService, onSelectCoach, onClear, onClose }: { visible: boolean; colors: ReturnType<typeof useColors>; snapshot: ReturnType<typeof useGym>["snapshot"]; selectedService: string; selectedCoach: string; onSelectService: (value: string) => void; onSelectCoach: (value: string) => void; onClear: () => void; onClose: () => void }) { return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.modalBackdrop}><View style={[styles.filterSheet, { backgroundColor: "#151518", borderColor: colors.border }]}><View style={styles.sheetHandle} /><View style={styles.filterSheetHeading}><View><Text style={styles.sheetEyebrow}>STEP 2 OF 3</Text><Text style={[styles.filterSheetTitle, { color: colors.foreground }]}>Refine your options</Text><Text style={[styles.filterSheetCopy, { color: colors.muted }]}>Only use these if they help you decide faster.</Text></View><Pressable onPress={onClear} style={({ pressed }) => [styles.clearButton, pressed && styles.pressed]} accessibilityRole="button"><Text style={styles.clearText}>Clear</Text></Pressable></View><Text style={[styles.filterLabel, { color: colors.muted }]}>SESSION TYPE</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.pills}><FilterPill label="Any session" active={selectedService === "all"} onPress={() => onSelectService("all")} />{snapshot.services.map((service) => <FilterPill key={service.id} label={service.name} active={selectedService === service.id} onPress={() => onSelectService(service.id)} />)}</ScrollView><Text style={[styles.filterLabel, { color: colors.muted }]}>COACH</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.pills}><FilterPill label="Any coach" active={selectedCoach === "all"} onPress={() => onSelectCoach("all")} />{snapshot.coaches.map((coach) => <FilterPill key={coach.id} label={coach.fullName} active={selectedCoach === coach.id} onPress={() => onSelectCoach(coach.id)} />)}</ScrollView><PrimaryButton title="Show availability" onPress={onClose} /></View></View></Modal>; }

function FilterPill({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { const colors = useColors(); return <Pressable onPress={onPress} style={({ pressed }) => [styles.pill, { backgroundColor: active ? "#2b1f2a" : colors.surface, borderColor: active ? "#f04488" : colors.border }, pressed && styles.pressed]} accessibilityRole="button"><Text style={[styles.pillText, { color: active ? "#ff82b7" : colors.muted }]}>{label}</Text></Pressable>; }

function BookingSheet({ selectedSlot, colors, snapshot, busy, onClose, onBook }: { selectedSlot: TimeSlot | null; colors: ReturnType<typeof useColors>; snapshot: ReturnType<typeof useGym>["snapshot"]; busy: boolean; onClose: () => void; onBook: () => void }) { return <Modal visible={Boolean(selectedSlot)} transparent animationType="slide" onRequestClose={onClose}><View style={styles.modalBackdrop}><View style={[styles.sheet, { backgroundColor: "#151518", borderColor: colors.border }]}><View style={styles.sheetHandle} /><Text style={styles.sheetEyebrow}>CONFIRM SESSION</Text><Text style={[styles.sheetTitle, { color: colors.foreground }]}>{selectedSlot ? getService(snapshot, selectedSlot.serviceTypeId)?.name : ""}</Text>{selectedSlot ? <><Text style={[styles.sheetDate, { color: colors.foreground }]}>{formatShortDate(selectedSlot.start)} · {formatTime(selectedSlot.start)}</Text><Text style={[styles.sheetMeta, { color: colors.muted }]}>{getCoach(snapshot, selectedSlot.coachId)?.fullName ?? "Open gym access"} · {selectedSlot.room}</Text><View style={[styles.policy, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.policyTitle, { color: colors.foreground }]}>Cancellation policy</Text><Text style={[styles.policyText, { color: colors.muted }]}>Free cancellation is available before the session cutoff. Your spot is reserved once you confirm.</Text></View></> : null}<View style={styles.sheetActions}><GhostButton title="Not now" onPress={onClose} /><View style={styles.confirmWrap}><PrimaryButton title={busy ? "Booking…" : "Confirm booking"} onPress={onBook} disabled={busy} /></View></View></View></View></Modal>; }

const styles = StyleSheet.create({
  content: { paddingTop: 10, paddingBottom: 40 }, headerContent: { gap: 16, paddingBottom: 16 }, itemSeparator: { height: 11 }, clockCard: { minHeight: 106 }, clockEyebrow: { color: "rgba(255,255,255,0.7)", fontSize: 10, fontWeight: "800", letterSpacing: 1.4 }, clockTitle: { color: "#ffffff", fontSize: 24, fontWeight: "800", marginTop: 4 }, clockMeta: { color: "rgba(255,255,255,0.78)", fontSize: 12, marginTop: 5 }, todayButton: { backgroundColor: "rgba(13,13,15,0.22)", borderColor: "rgba(255,255,255,0.24)", borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 10, position: "absolute", right: 18, top: 29 }, todayText: { color: "#ffffff", fontSize: 12, fontWeight: "800" },
  stepHeader: { flexDirection: "row", alignItems: "center", gap: 10 }, stepNumber: { width: 25, height: 25, borderRadius: 13, backgroundColor: "#2b1f2a", borderWidth: 1, borderColor: "#f04488", alignItems: "center", justifyContent: "center" }, stepNumberText: { color: "#ff82b7", fontSize: 12, fontWeight: "900" }, stepCopy: { flexDirection: "row", gap: 8, alignItems: "baseline", flexWrap: "wrap" }, stepTitle: { fontSize: 16, fontWeight: "800" }, stepDetail: { fontSize: 12, fontWeight: "600" }, dateStrip: { gap: 8, paddingRight: 18 }, dateCard: { width: 66, height: 78, borderRadius: 19, borderWidth: 1, alignItems: "center", justifyContent: "center", gap: 5 }, dateWeekday: { fontSize: 9, fontWeight: "800", letterSpacing: 0.8 }, dateNumber: { fontSize: 22, fontWeight: "800" }, todayDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: "#ff82b7", position: "absolute", bottom: 9 },
  filterSummary: { minHeight: 76, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, padding: 15 }, filterSummaryCopy: { flex: 1 }, filterSummaryTitle: { fontSize: 14, fontWeight: "800" }, filterSummaryDetail: { fontSize: 12, marginTop: 4 }, filterSummaryControl: { flexDirection: "row", alignItems: "center", gap: 5 }, filterSummaryControlText: { color: "#ff82b7", fontSize: 12, fontWeight: "800" }, filterSummaryArrow: { color: "#ff82b7", fontSize: 23, lineHeight: 25 },
  slotCard: { padding: 16, gap: 13 }, slotTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 10 }, slotTime: { fontSize: 21, fontWeight: "800", letterSpacing: -0.45 }, slotEnd: { fontSize: 12, marginTop: 4 }, slotRule: { height: 1 }, slotBottom: { flexDirection: "row", alignItems: "center", gap: 10 }, slotCopy: { flex: 1, gap: 3 }, slotService: { fontSize: 14, fontWeight: "800" }, slotCoach: { fontSize: 12 }, slotArrow: { fontSize: 22, fontWeight: "500", color: "#ff82b7" }, openGymIcon: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center", backgroundColor: "#282130" }, openGymText: { color: "#bba4ff", fontSize: 18 }, emptyCard: { padding: 22, gap: 10, alignItems: "flex-start" }, emptyTitle: { fontSize: 16, fontWeight: "800" }, emptyMessage: { fontSize: 13, lineHeight: 19, marginBottom: 4 },
  modalBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.64)", justifyContent: "flex-end" }, filterSheet: { borderTopLeftRadius: 30, borderTopRightRadius: 30, borderWidth: 1, borderBottomWidth: 0, padding: 22, paddingBottom: 34, gap: 15 }, sheet: { borderTopLeftRadius: 30, borderTopRightRadius: 30, borderWidth: 1, borderBottomWidth: 0, padding: 22, paddingBottom: 34, gap: 12 }, sheetHandle: { alignSelf: "center", width: 42, height: 4, backgroundColor: "#4a4a52", borderRadius: 2, marginBottom: 3 }, filterSheetHeading: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 }, filterSheetTitle: { fontSize: 22, fontWeight: "800", marginTop: 4 }, filterSheetCopy: { fontSize: 12, marginTop: 4 }, clearButton: { paddingVertical: 7, paddingLeft: 11 }, clearText: { color: "#ff82b7", fontSize: 12, fontWeight: "800" }, filterLabel: { fontSize: 10, fontWeight: "800", letterSpacing: 1.2, marginTop: 2 }, pills: { gap: 8, paddingRight: 18 }, pill: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 13, paddingVertical: 9 }, pillText: { fontSize: 12, fontWeight: "800" },
  sheetEyebrow: { color: "#ff82b7", fontSize: 10, fontWeight: "800", letterSpacing: 1.4 }, sheetTitle: { fontSize: 25, fontWeight: "800", letterSpacing: -0.5 }, sheetDate: { fontSize: 15, fontWeight: "700" }, sheetMeta: { fontSize: 13 }, policy: { borderRadius: 16, borderWidth: 1, padding: 14, gap: 5, marginTop: 6 }, policyTitle: { fontSize: 13, fontWeight: "800" }, policyText: { fontSize: 12, lineHeight: 18 }, sheetActions: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 7 }, confirmWrap: { flex: 1 }, pressed: { opacity: 0.78 },
});
